apiVersion: v1
data:
    db-encryption-key: ENC[AES256_GCM,data:zdutkjS9E4JNOEEXTl/4lWQssLQEshGdJKhUwdNc59KN8JpYrzGLMSCUa2ReEEZyHFvxNJlbrTPVe7BG4eDNsTWRYoR3yhkJ341wKHISK7/zfHY0S3Sd1A==,iv:IB9a1WKtVn9fWNOnly8hLbekwCK7K/R9PpR2bMejof0=,tag:ic/IU1lN9CQmlLUzvKxK9w==,type:str]
kind: Secret
metadata:
    name: db-secret
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbDZsOWY3cDlQVmVKaGNj
            YnhxcGZrNWlXS1ltYVFabjdqcVNWZktTbVVjCkNXODNUOG91ZjQ5R1VON1h4emdQ
            cWxNSXVzTW9aYVIrR3JmeCtMVGpVdTAKLS0tIE9MOXB2OU8vbXBubnF3VUI5SHZQ
            L3pZUUdXNHN5RmxkN3lSbHQ0UURBdG8K17bachxsp3P6myAO6w+TnndKZZhZXIJG
            Ol3fQ8H35M6E9bOUniv1YtLbQa45mJyDtfS904vrbxWZrt3S1fFPKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-25T21:14:04Z"
    mac: ENC[AES256_GCM,data:ztTldRsQE7k7B1y/tVQXUuv+jllXed89qKpUEVweU79qxFHnYgpDjUl1x1iM4ysUPO9/wJNAsLFnmisPLMNQfKRB1agFDYW8Vl8flZf6R2i2gVgVvY5bN78d8Vt+2aSSg7xOOjHo/NLx/suqCwUpCP4Hxm3YiYeNehS7i0bj+Lo=,iv:iy7cWK02tZeXgcmP7bSI32CHkkyV/3APZNLUnoyUb9Q=,tag:GpGAo7nFIMv1SJqetco9MQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
