apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-redis-auth
    namespace: chatwoot
stringData:
    password: ENC[AES256_GCM,data:VGBD7hh+JzDNlWDPvW/pSMeWHWaISD4hY2koKoH+bCR/5heo6JyrxO0cKMt4UMAR,iv:JPGtD8vj6i8aoA0mskmyr3Y1UMBiaObf0wHNo8hQeOM=,tag:xAJbhAcUXZelBs8ymuVW/w==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBbjZSYVpYRE1qNjZiZzdM
            N29vVVI5WTI0M2NMcEpXcUp1VWFHbjlZRTNnCkN4d3RzTkJKcmsxTkwySjdSSnJs
            aWVyMHVxRWFic0s0OFZ5aHBlV0xtdE0KLS0tIE5iQ25ISVA1b3FPUVh6SWY1bmwy
            ZE1Fd1JJZlFEREpOS21sdkI1ZWEvL1EKDhfhj/Uci+X9hhBTaqh1sK2Fp2xYtWq8
            vqHCIR8QfjEcG6Z5Y79X0VLXGJ8hoVcJI2Vm6pMTaa5RyNEfT4vXWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T17:33:50Z"
    mac: ENC[AES256_GCM,data:dsNw1uqK23zuZgPtIDp2QWtrir6mAbb06WF829tHEOzDjN8oUqL1FCEK+GB+1wpzPFrSyXMnt+gSrWjHCKKp8wOndBcnO7I1j0sINi7rs/FFHMWHq21keyUBxP+mKgOho4Y8snr8+OzNPU8ew8VzxnPbyyTGp00ogyVRQfCErjk=,iv:Fv7TF0B7pLFoPSemaztRwdsMkWzA4dhg9j3QUKWqhA4=,tag:E1k/kQZgt6cOoN2LMqnxrw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
