apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-secret
    namespace: chatwoot
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:DnTaYf3T5bl9pvWDWwALlwUM1dsy4dLPL3lCsKp8wOz5A5M4ndOyi0u774dMcBVaz08aELXLAhNQbLgKdA1m9SA1ee0SvWB/l9r4tBWZDVtM1SPV4IQQTu6cvwaHP6QAGR/yUtEIr5piAWkIRpvsEqq504Bx85DhT/cd36iGNrw=,iv:ZQCr/TkbZhSP0gk3Iuis//jMNLaYbAaBIgPq22mNzdc=,tag:MBsaEG7i0P2Z38KB7K13TQ==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsM3l2Sno0eE5yNHBGd3Jp
            cjlTOWNnVlVFN1dGREhrT0RWNzVrU2h5YkhJClh2bzgzNGt6SWhQbkVkWm02bjFv
            OCtEeWpsZXF4dFZJSUorNjg1ZEVjWUUKLS0tIHFubCs0aEhmSktUejd0aUFGd2J0
            Z3AxaGJrcjMxcEEyRFRhVEt5UVQzRUUKbQsC7YYh+DQN8lYH0NAoCBCOIqfpehCz
            4NN5y+o8fq/P/yDM5AswKvQZJHCVdWKJSZjSl0oS5a+5QR5VPFUZ4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T17:58:46Z"
    mac: ENC[AES256_GCM,data:zIPFMZFyHTBOOPPTIFpGTAnDrZBhMKA+/c/CPsWmLZWiG3PTIP7j1yZO/FBVBQ+dZ91zl6ffqjJGDrC+9L3/WSdPoDXh8PNZfoyCyC6KyqCGMOyU3x/5EUVblDdo1FTkaqiy+VBeDNzjHyOrcoM44d7k0+SS9C3mjqa5eUsWl38=,iv:wnp6b2rCXBcYIWyurk7lX5kWkjWJE7AJHLB3+eRehyA=,tag:Um8mLRNxtHPADdiW3ueRCw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
