apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-smtp
    namespace: chatwoot
stringData:
    username: ENC[AES256_GCM,data:YagB4VwwFRAI/uiYqATj3CL6UWLmdtF2,iv:3QEYsiT9gk329tSTmXoA9r7TKGkMfyfcSz7i6Ce+BAU=,tag:YsTYgFLLDJD+xKOfVe0Lyg==,type:str]
    password: ENC[AES256_GCM,data:EWOuZR8W59W69FbO4El3tb1DFpeUSZM/bXKAF9KU2UC7wPiaJp0DX3I7Zu5GBsJNogwfEaM4eoT0iL4eTYUi82Qq4AcJ/a4e5kD0XEIcHBDSORAhTSFAlx+Z,iv:uJy21htuXt0fS4GbFEUz7c9WJpL2MdO9YVk9jE9c2fs=,tag:Jxud88UQUL6gSgr7JF8+cQ==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwSS9Fcm0yNWRaUUtmTlRK
            dis0WDZqNTNSL0V4ZlJlQzhHT2IyNUM1VWp3ClNQRDJTV1BVZEVNdWN0S0FBUnBW
            N1hqOGs1Y2pyUTcwbldGMFIwME9FY3cKLS0tIHovVkRtRW5QQ21rZ0ErVkUzRHR0
            TzVsWllSZ2x4cGlETk0rUis2b0hSUU0K1G6szZLf/KDrsbO7A51j84KQUyvmBllc
            rW66q1PuwCXjKpXOSaIUvcAzcmYfAqcJTOvr8TiJApHhaHkvORx6jg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T22:56:53Z"
    mac: ENC[AES256_GCM,data:QKpMaEj8eVX3Ok5Zw5f54gE3FLaa+POFNhPwNx4wRQcChUsia5KwXNYrAHRbW4Fun6V9Bd04mquQyxMKtyQ/6zh3y2TDPQGV6tspU88owKrANXg/Wl4s7eB9aFSEvL3IQp0Svuf8Z/mRC1h9K+PmDil06UdKI9CF/GiVzPZFtvQ=,iv:FGdFA7l6KJTJ1IQpYHlUqMeRT7wS923sSXnJORJmGdQ=,tag:RfU9IkqiBPksrxU1IoxJPQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
