apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
namespace: flux-system
metadata:
    name: gitlab-registry-secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:ENmxyekmmBEbUR9TUPdnxdD4IKNkxgUtbWZhhRUpi+ob9aGp0NcL1nOVgt+47TXYONe7crSPmsMDt3MuuLRg9Rly1bNtVYrDBG1A9UOY2qcVPzJxr9fuEgi2OO1U1eeeT3ijAh0W/T2/cuS7IHjQGWpyglwhGP8mAX+if/+nB076xj923bhtVPp4BvV8RkmsNpCBV2WQXZWar8sYMu6hIbKNxnHTqX71y18kHnVPrFq4JPeBXwd3VCnrSCS7DFvdLKaF6w8Nmm+xyhlBzhJStJIwZfAEeLrzWA6hRTWUHd/+anArfcO+/VCxsGk0jGguaA3Oqw+pyymc6AGO+3EXzSTPC21xDlFqSCjApWUIVAnvS+MJDAcP+HSW2CapXhtxlGEzLZHcmk22T87+6fA7oqxUCGSvojQyC5aYDDD4pwY=,iv:Lr/7mTL1oaDqzmT6SKVkounErTQTKyxihYS5qeEKA2k=,tag:Sd03Zh694qBjLp0iEP7fvQ==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYkpBYVBOWDFZWnN3dnla
            azM4T1RvSStKd0dzMGhYd3RUL3FOWkR5T1dVCktkNUJNd0FUMkkvc29uZXBCaWRo
            WkMyWHBnamljblFlZ1dhQVhOYWFlMjQKLS0tIEhMOG56N2VXdUZUVktnTkQ1UWZC
            QThqQjJmeldOZE5UbHZZQllsemhTS0UKADT3XXY6PW3HBs2uabl/Xa0SSAg4y7uU
            AEL073I+5meNBVX2GUHe9NuPfX0yszfiHeLrp7C8FYtxWGvJde5Qcg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-13T15:21:22Z"
    mac: ENC[AES256_GCM,data:+hvpUB786HYW1ltMeyOsYQVM5JTs4tlhSVcahfdNJlTp9WwDQS98jNQTssVOAto1LrTROD6jlxjIhzYbeNjZLJ1auYhpku37P2I+ucyA2vD4YMJDAr75AaZfOcXmMOuus/cisO0/MlI2RSlF0ogCXLtySzFaDqhskETUDu+QNk8=,iv:r/U8V7BDJKBGWoYXaH1ziIQYW8cH2ke33fgEf8hjPuY=,tag:tfYhuLtOgPzD9+4HzFiqew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
