apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: media-feature
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: feature/media 
  secretRef:
    name: flux-system
  url: ssh://git@github.com/Justin-De-Sio/homelab 
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-feature
  namespace: flux-system
spec:
  interval: 1m0s
  targetNamespace: media-feature
  path: ./apps/staging/media/feature-overlay
  prune: true
  sourceRef:
    kind: GitRepository
    name: media-feature
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings 