apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:bR9AxT9KZO+cci96+pKeqSZzmDooEz0Ew9uTWSEsP6rxA2b3VIGIgk9uRJ/q/8LrFUGVYwY0GHnew2A2FCYl3nHYG3/YaodtrC0zA4EuWaqeb1PV0x8DmZmyaMQ2sLVjC8XCKVBGbg4yEJgZvFAfpVxgALpUyJRbB1eV8RmxjUT0cp7f3KKtACVFMKprmzG4igurKyX5DnH1xA5TBXOlVF5PteBhejjihC4EGbiBfVtEILGD4Po7Nr/s15sb2255C4/d51bNs4oL1jR8hV3mj+7aGL0oU2R8shZPqSjt2jJsdNMNJ6DomPDpk8sUomtNT3m0FtOCP7a240Dv2AU67+824wg=,iv:d0mj7EvNlvWHW6wHQWerK09+EUrse+I594DnJmadCe8=,tag:c3zN1ySTV7qV7aXVxXdAYw==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUmUycTQ1czQwOGQzd09k
            dHNRQ0MzeUhLV1lia2hOYTYzWmJFSnNta0IwCjh4cXB0a2pYbERDcjJLSWowTjk3
            dFJIU21DRnFPOHdPWlEyR2JJWGhOSDAKLS0tIHB2RmR1Y291azFpaHVxSng5NUVL
            WUs0S2VKVHUzSkZPd2cyck4vVUVqSkkKMxH1ifdbjP35ex18f12HcpcNq/I5mIDQ
            qkKXewWtO5+Cr02p331KhyIttMJbxqT+j7qdXcrVY5W7QdnFW/iJ5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-30T20:17:54Z"
    mac: ENC[AES256_GCM,data:ffcXpvyvWvSpzB5A8Hg2k7irvCDb7WngqIgNcPujsYLv1Beev4XatI2W/Yc30hi0TnwC7M8UD47yC/0Dew47cvQu5VxjxUZhdjYNYcv+0YLwJ4oMEbdF59XpaPLpdxk7JmhsBl+7IostRwu2mE+ZrmJrYknrZfTZXNSxoKPV0Sw=,iv:l+yNQa9WONrWnYqKxsS31l41KP+igtyvkhTYPySUHMw=,tag:jQvjVFliX0H13yx2KZ9ybQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
---
apiVersion: v1
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:lnlyCrknHZ0=,iv:2pY7M4AXUY2ueoWpyv3pONpoQ2ZM6fZm3TugzvQzzDk=,tag:Eqi5dOL/VfVMH+AZatwDIg==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:+eTWL7LM8RwB+M5SkA0BzwqHUWsNX0hZhiIlomcj5hyffY7eO7Mxtg==,iv:+tcfbYF4TUpwp8WgEruMxrRz95ebI+m53qA0Tjt5jmM=,tag:Jm6f6Ydf3ODlVQ61GlSPNQ==,type:str]
kind: Secret
metadata:
    name: linkding-credentials
    namespace: linkding
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUmUycTQ1czQwOGQzd09k
            dHNRQ0MzeUhLV1lia2hOYTYzWmJFSnNta0IwCjh4cXB0a2pYbERDcjJLSWowTjk3
            dFJIU21DRnFPOHdPWlEyR2JJWGhOSDAKLS0tIHB2RmR1Y291azFpaHVxSng5NUVL
            WUs0S2VKVHUzSkZPd2cyck4vVUVqSkkKMxH1ifdbjP35ex18f12HcpcNq/I5mIDQ
            qkKXewWtO5+Cr02p331KhyIttMJbxqT+j7qdXcrVY5W7QdnFW/iJ5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-04-30T20:17:54Z"
    mac: ENC[AES256_GCM,data:ffcXpvyvWvSpzB5A8Hg2k7irvCDb7WngqIgNcPujsYLv1Beev4XatI2W/Yc30hi0TnwC7M8UD47yC/0Dew47cvQu5VxjxUZhdjYNYcv+0YLwJ4oMEbdF59XpaPLpdxk7JmhsBl+7IostRwu2mE+ZrmJrYknrZfTZXNSxoKPV0Sw=,iv:l+yNQa9WONrWnYqKxsS31l41KP+igtyvkhTYPySUHMw=,tag:jQvjVFliX0H13yx2KZ9ybQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
