apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: calcom-database
  namespace: calcom
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 2

  primaryUpdateStrategy: unsupervised

  monitoring:
    enablePodMonitor: true

  backup:
    barmanObjectStore:
      destinationPath: s3://cloudnativepg-homelab-backup/calcom-database
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cloudnativepg-backup-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnativepg-backup-secret
          key: ACCESS_SECRET_KEY
    retentionPolicy: "7d"

  storage:
    size: 5Gi
    storageClass: local-path

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
