apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homarr
  namespace: dashboard
spec:
  interval: 30m
  chart:
    spec:
      chart: homarr
      version: "3.14.0"

      sourceRef:
        kind: HelmRepository
        name: homarr
        namespace: dashboard
      interval: 12h
  values:
    env:
      TZ: "Europe/Paris"
      DISABLE_ADDITIONAL_FEATURES: "true"
    persistence:
      homarrDatabase:
        storageClass: local-path
        enabled: true
        size: "1Gi"
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"

