apiVersion: v1
data:
    ACCESS_KEY_ID: ENC[AES256_GCM,data:your-encrypted-access-key-id,iv:xxxxx,tag:xxxxx,type:str]
    ACCESS_SECRET_KEY: ENC[AES256_GCM,data:your-encrypted-secret-access-key,iv:xxxxx,tag:xxxxx,type:str]
kind: Secret
metadata:
    name: cloudnativepg-backup-secret
    namespace: immich
type: Opaque
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            # This will be encrypted by SOPS
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-01-27T12:00:00Z"
    mac: ENC[AES256_GCM,data:your-mac-here,iv:xxxxx,tag:xxxxx,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2 