apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: immich
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:KHGogTmlS8E8hYyZgCgt9sML47pomv2wRpxo+YweBZ6s+R3RchobMA==,iv:pFtXk5mj0jksDN4sYNJXDCUHCvbl0+24zpa5YHS9VGM=,tag:ET1CxAIm0pDNoWsAkdJH+w==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTHladld4Z01kR0ozRW5G
            ZUh0Nkt4Tms4M2QvZjVuRG1VcFFpcFNwZzNZCjlVM1JmMFNlRDhrcnRMYkl1dXVm
            elNSNnZZRnRsTy9DVENuYmpRS0Z4aHMKLS0tIG4vdHlDdWVYSXJTWU5kemF5TXBj
            aEJQU3l6M2tTZEVOc2x2MS9nWmVVaXcKjBOORZTclnHwC2gmyE1EFTC47w7pB1EU
            rVg6YGExnSWyeeX1WQtg5ULPhxG41rCWw2Vl7tUUXei6YyaS1JwSkg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T20:19:20Z"
    mac: ENC[AES256_GCM,data:V/IqMnR/gAQKwHNOZIP0W+yA7Uqku8SuorHcoLliydjCnpFaptXHUNVmQyKhlbulNQxxwQfNXz8YDSyjuS9GiG7Gk/PD5RVCmKeRgZ5lHCdmbJGJXuCsUd2kXBa/dlePxgQzdRomY3Om1Lt7cmZ+3zjDaj4HoN8Nni82RXPTnfE=,iv:Te7nwZiDYX4uIAF30sTSn8jAZLUsfiUvI7Yd2YrnG4s=,tag:qI6PX0yFARoLFWV0urPHLQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
