---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.9.0
  interval: 1m0s
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: false

    defaultBackupStore:
      backupTarget: s3://longhorn-homelab-backup@s3.eu-central-003.backblazeb2.com/
      backupTargetCredentialSecret: longhorn-backup-target-secret
      pollInterval: 3600