---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  chart:
    spec:
      chart: longhorn
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: longhorn-repo
      version: v1.9.0
  interval: 1m0s
  values:
    # -- Setting that allows you to update the default backupstore.
    defaultBackupStore:
      # -- Endpoint used to access the default backupstore.
      backupTarget: s3://longhorn-homelab-backup@s3.eu-central-003.backblazeb2.com/
      # -- Name of the Kubernetes secret associated with the default backup target.
      backupTargetCredentialSecret: longhorn-backup-target-secret
      # -- Number of seconds that Longhorn waits before checking the default backupstore for new backups.
      pollInterval: ~
