apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

resources:
  # Core operator installation only
  - longhorn-namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - backup-secret.yaml
  - node-configurator.yaml
  
commonLabels:
  app.kubernetes.io/part-of: longhorn-storage
  app.kubernetes.io/managed-by: flux 