apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared

resources:
  - ../../base/cloudflared

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: cloudflared
  - path: secret.yaml
    target:
      kind: Secret
      name: tunnel-credentials
