apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:ln9tcgn/GNM1cTN+Ly5sJK0WkP24U8CZ2ZDyn2LBO7O6pnAge10TI4csbfIuyJkZ8rTJffX63T11yKXvDHXnMgzKe2sd4KF8q5aHv7OrlFZqhXzfFouo8V4sxkFqfPBGXnTXPmpu5bISiDPpppfst0szaPHFy2xuri/Ah1y9dI8RV9Sg6yInSEwJq7BjYvlZH5I3EZ9THFvKTYF7ZhHoEn8yWuDj+rsHDUYK0py/Y4Bn+Ndrp1/c/Q==,iv:OyBlfypFmFYK7JP0j+DEwW5cAd4IusMjUXTp/Wv72jc=,tag:lgN3pzNA5LbOUfdyW9qB9g==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrUGo2bHhsZWQyOS9IQVBK
            RE5RV2VXMVNrK21FNEt2elpyeWkrc0d1d0JFClRFOER2T0N5TTFpT0FCeExtWEFy
            ZklUU1hKbEg1WVljMmpueE13S3EvS0kKLS0tIGZCTGJWYUNqdFZqcTlFMmU3ZFhJ
            Y0U5WEdReTJuRGRSWS9HdFBycGplcGMKXlBzL7ehruTxt03CyVkUZWmmkTg4U5a+
            0GsDabBv+q2gAu4iqUyfldLPQdCc6frqZm2jTQyh7U/72zBhHBJWjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T16:18:20Z"
    mac: ENC[AES256_GCM,data:F6Eu+PSMyShP2zOR9VLryU1ZgzBfKSk8Wh+FKNhO7Fb9375wtDuIGbQphMJ+YznqI6lDG+zOdx3E29NBj0279hcrQnysStEppnJyD8xjHWUI6CgsUx6/RgyKg5NIlHc63T4rXWJNnBRzpVEy6fkBLevzTaljq5ZbRcPGhVXlmMM=,iv:qDlpO4FKfHQgnNYiv19FFLyNJo2BdjSJV0UjYXt6Mrw=,tag:xTHy3GiytOv4Xq39meiTaQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
