apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
stringData:
    token: ENC[AES256_GCM,data:3WrxplI9aFTKDIkE8zEeL8NnxX9MFqSiSaqfjaSg6H6G/gf+nXKpDwdtk1KC0iVGajgBkQtYyw3KpMc/kicTtMj42yxoheghMcMmLOVn27zseGZ2wrWavX1ln1nJQIax4agC79J4UlrVIQ8pukMoylUFd/bYK8lv8wlLq5pKbjM8isApHPml/lRwmEjflEL0SbBc2h+Pv4AZ3YN70Spx8jql1hN1TV8JQCyFSay2QX/xBWlRgzYdcA==,iv:jm7Y2klMCux46XGYVQLJ7cCUav2e6ezmi4N3Uh2wolM=,tag:bim8zUMhZECGSyw9GgUezw==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSdHpDOStFUTRZU2RheGNr
            NUpLTEpHVlVqcUFjOG8rbXk5Ykg1Skp3eFZZCi80Q2hqL00xZ0ZCQklUQmR1aEJp
            bG5xUTNMSFB3NkhCYUJYRjI4RFZycFEKLS0tIDZnU3hZYUxqTC9BeStBWExnU0JT
            bHVRZHl4NHR5YWZ3dlN4ekphNko2cVUKoNHF0/2Qrq94QDcMshc1EvoxezIpGfX3
            G5t5qJnHx++5+o0oFjN6oFv2hUYO6UxjqZ9fTGT95WsaeCn/9D5BOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-31T18:27:01Z"
    mac: ENC[AES256_GCM,data:i4l8d7EEDuZqk1Chv61eg/Qdld+KwjhpNozA/pzkxa3unN3I2rTFwq/BlsAnmYDQ0YdkddNwo1u7XRvAFdZ1SST8yN6r33EFwWbWkxWvvv/wQX3xDm+Nc46gcEb4LQQNRtms1A6OUGqdfc55lLkE7IOhwrJ2Rofp7B0vAdviccQ=,iv:XEg5BP420Kcfc4mjrxFWIjMxjKyn4j9PNMHo5dLDKFg=,tag:o10FHF97y+5yt0MdZ2YQHg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
