apiVersion: v1
kind: Secret
metadata:
    name: calcom-secret
    namespace: calcom
stringData:
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:jS/lbfQMEAucIGuw8IaQPqJ9g5jAv9ItpOYUknfEECpBdFfK4YPTd96U+4g=,iv:KmOC4I8MrhNfKQO4CeQjqPlI82MPU3eF11KaY3qNUKY=,tag:agPk92lI9HpO9+7EgKK3TA==,type:str]
    CALENDSO_ENCRYPTION_KEY: ENC[AES256_GCM,data:YStjbKLVIaSh5UFfjW7H3+Ptt75hz/u5t+vquRss0zc=,iv:1aeIexbmjErw0V7x+3g+wEnRa7EJ/yId/cClwfyasMM=,tag:r5HHMChTIoqm2PWz5tb7cg==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyVmhVSnlmK0tRaFgrbWVq
            Wm82WmNaZ1RDNDVlN3poNEx0MFNLVFdLcDNBCkZNVU9LbXZGMnVGdUNhdlE5S0Jo
            WkN5eEErT24yQVVUSHVxcUI1UCtCdlkKLS0tIE02ZS9qVXE3bVlqU1Q3V2R5SmJY
            b3E2OG1TVm5VeGFTNGpwdGdncTlHcTQKCTfVA6yaanGcC9+zIGUU1K/+At9wgpri
            YZUZWRbpEDuQaqsFUB87D/dd0TXpkKQKhP+5prTAktQ46Moek1QLlg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-25T20:04:14Z"
    mac: ENC[AES256_GCM,data:OmwaYXF7z5Hq5RL9qqH4KH+wZZRIMhAMvq0LIvIFKcW/L4fHvX3SdoKn/rtt1hLwBIx7H2xC4YAJPUar1+CwV867AgK25whxk2pL2QesxaRWDISE5XNeCJV0yKdGrvooQgy1WkfRQzSLdGewjsl/msd9lM4tR7z3pWleoLq91CU=,iv:w+PbFGvmMbfV5vToVx/0e+1vo5BXjXEd5Tq9CuwSVgg=,tag:Dmo/IiJbIbFhBmknhjkA9w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
