apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: secret-env
data:
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:1G1gW8NeMTFXSaCkkY8t6EHqNSBpBMJzyCE724FPp6fq8+lQcoUweMFSqCnHZeadUBhJOjHZWLW+N4LR4f6iKBoSe8P3NxqoufiX2+r3JHhAiIpw7DAgVsyZIizjeeNamI+CJDvUV88he3NFh9XMpHUaYZXmGW/Vw/HTFK5RINpe+KWQiP6fBSGIXv06T9oP,iv:FfBOgSmY6aCAI764Wc2DnNYiGI8BMJfFoxeQX9AxYi0=,tag:E4fZL7c5/8sOUW/9DFhsLQ==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:D9VXvEYEgEqPdNr9dmv61Bg67NstmyCvcmgXCndzDW+2ChZTSzg1yCy+hp5IeHkqvXzbiA==,iv:uLnDDc/d1i0+SrKx23sTMjnIlOoPyGh5dDQgM3D4w14=,tag:MM4NSrlq+7W0skk3UhKEqA==,type:str]
    SUPABASE_SECRET_KEY: ENC[AES256_GCM,data:3/AMD1Im0RBJGMQV13VUoJX3beCxRAKxjffncjDQPsJIxW8r/mAzlcW2+sYau66uBPIMKh1X+CI=,iv:mqHm/3KJ39R1WiqQ0d8l4GC2fq2ovnMI67N/A7SMr2M=,tag:cv0HMokX52cRqezQY4chNQ==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5QUZpdjNiejZrOUxzcXBn
            MDYvb3Z5bjl3ZzhVSWN1d0V3cmhEb28wTUJRCmNNSW5FMm5USnVrNU4vUHpxTS9W
            bHBTcUx2UXJ2eGJHcytjQVFuL09EZTgKLS0tIEFMaUpLZWlmRVRpZk52ZzJEN2lW
            T3B2TFZ2WjhxWGFPNEZGKzg1WkllOFkK5rHCv1YFw+j8I+cBzmflEHiNIfAGSzxY
            RsqJUxoPDg4cvOPHVbI54KfhHJBbC1M+1kj7C2elNqezlGX6qkhbUA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T21:58:45Z"
    mac: ENC[AES256_GCM,data:iwhknutfQH+4SEvvIs0gPOqesjSSmkn0dFUMutx3bh2XEuDtHbrcBiuxrKIqPGmNamQTV+qooMsl7cdKw81uws89ZFNrxDi62iFk3BUoL4nxU0wOYtdVPNVrlPVUFgVLEaSXnZ3SoxN4bLnXt/3KMDXTXMCp0Pc8v558yV83GM8=,iv:uq2tKeV55CO+A0L5rUkoHev4CixN2UQEseGiWQFDXAk=,tag:sJjUsWV3GsUG1GmyzBdIzA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
