apiVersion: v1
kind: Secret
metadata:
    name: secret-env
data:
    SUPABASE_SECRET_KEY: ENC[AES256_GCM,data:+zjoDovvzV9UGgNVVpFO9UiMGKuFPelFHvcCzMW01Q8FTx78oRcvTZQp5vRhfY5JSWwB9kF69Jw=,iv:Dgj326veE5oysuWXq7hYsKG44Xjmj91IBwbucHlom/E=,tag:k2i3+ylvHDeXVqtFgNycxw==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNE9DWmZueG85T2ZSSXpK
            Y3VvS04yNjNDemR3NHBjMG0zL2ppMXBJUVVFClhhdFFXTnlDa0FHdlRFcklBekdV
            RnQyR2lpMFJOT0dueGk3L2tnTDFIZ1kKLS0tIERmeUw4VjgwNDVjdU45QVZPY0JL
            ckwvNGt0a0lLTzU0RnJUb2tSUkEva00Kiq4EIbkM658OiPshfAYdxJ1txElZP6Jj
            3VJAgLl6Ly8Hg7/LTB4BAII23qsXyxEomSALu4oDuUFqSPqMyZEzBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T20:43:15Z"
    mac: ENC[AES256_GCM,data:B7oWN2e17aIQsxI203i6QawLMIHbVv5pQ7Hr/SmNr85ToUp5FpKVPiSHiDu4L2KIR9jzO8JHwSZUgxZjW8OVchpjyNClUz5kHHK4+7l6Mgdirjb/MhCzKE351q6C6mJY0YnCWsnNfWGqU9WJF3Zoy0AVtDBNg8ucvMQKhXSPI9U=,iv:ME9bRX5fVMVJdd0bEKTbS5ShPAu6vmQpkB/8AI/N+n8=,tag:GjjPFSyiMxfPNLkI6mr6xQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
