apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.x.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: homeassistant
  values:
    ingress:
      app:
        enabled: true
        className: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: home.justindesio.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: homeassistant-tls
            hosts:
              - home.justindesio.com
