apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  chart:
    spec:
      chart: homeassistant
      version: "0.3.18"
      sourceRef:
        kind: HelmRepository
        name: homeassistant
        namespace: flux-system
  interval: 15m
  values:
    ingress:
      app:
        enabled: true
        className: "traefik"
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
          traefik.ingress.kubernetes.io/router.tls: "true"
          cert-manager.io/cluster-issuer: letsencrypt-prod
        hosts:
          - host: home.justindesio.com
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - secretName: homeassistant-tls
            hosts:
              - home.justindesio.com
