apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.x.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: homeassistant
  values:
    controllers:
      homeassistant:
        containers:
          app:
            env:
              TZ: "Europe/Paris"
    
    # Mount HomeAssistant configuration from ConfigMap
    persistence:
      ha-config:
        enabled: true
        type: configMap
        name: homeassistant-config
        globalMounts:
          - path: /config/configuration.yaml
            subPath: configuration.yaml
            readOnly: true
