apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  chart:
    spec:
      chart: home-assistant
      version: 1.0.0
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
  interval: 1h
  values:
    controllers:
      homeassistant:
        containers:
          app:
            env:
              TZ: "Europe/Paris"              # HASS_HTTP_TRUSTED_PROXY_1: "10.0.0.0/8"  # Uncomment and adjust for your network
              TRUSTED_PROXY_1: "192.168.1.0/24"
