apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 1h
  chart:
    spec:
      chart: app-template
      version: 4.x.x
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: homeassistant
  values:
    controllers:
      homeassistant:
        containers:
          app:
            env:
              TZ: "Europe/Paris"             
              TRUSTED_PROXY_1: "192.168.1.0/24"
