apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nfs-provisioner

resources:
  - namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml

commonLabels:
  app.kubernetes.io/part-of: nfs-subdir-external-provisioner
  app.kubernetes.io/managed-by: flux


