apiVersion: v1
kind: Secret
metadata:
    name: postgresql-credentials
    namespace: nextcloud
type: Opaque
stringData:
    postgres-password: ENC[AES256_GCM,data:A9TUVxY7KZlByfOmMJ/O9zzsxmnsF3/ZeCr8zRz9UcA=,iv:6Sc119um11o857UuFvTsZRslmhPXkf9bdxmFqAELEks=,tag:gURV3yesJXX8uadZlKinUg==,type:str]
    password: ENC[AES256_GCM,data:Pp+jsVXUJWIQOUCEwamE/Q==,iv:GbsujbNj8uVeG9ocOkFid+/6y9/Fr+PurF1RjvbwMo0=,tag:lf0CTCdbF/+IW65RwnZOlQ==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NFExSkhjSkZTWXZVRkVy
            OXRJWjN2aUo1M1V4QUJOOFdTMUxCaHpEbnhvCjhJQWIrTHRYUGhILyt5MGpaRlpK
            cTc5Y2RsV2g3QnRVVU9vZE5Jb1ZkZkkKLS0tIGlVcXIvSDl6SzlDcHFFanJ0VVd1
            aHpqMjJoVjNmQUdzaFRUNkV2elRZR2MKPamWRXJBXeFX+usFUPzEPSFrPpyz2UEg
            RoPYgMQKMeNidrjIaM/pbId7+iPgLW+5ReEXN6P3mZxeYgmv0RfYgw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-01T18:06:28Z"
    mac: ENC[AES256_GCM,data:Q55BojQPMBFMo0bEQjSeO6eOwnrftsofMaI337+dUelfuZLhB7rG6PI5PC33kZzLnC7NPIQhnM6v4OP5bZqJUJSO1ZXLiC9vQ9szm7tRh2LAwBBLI2ERqGgiGKSu5pZFu1DfA1m9eORO7o891+fOUyFmGyPrh3BX43G+MT1NnlM=,iv:SAMAMnyT2Q3jmncRaE/YOkcD+CJZlD598iCQY4dNEdU=,tag:XGDUyHLC7b+zeMujehpv4Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
