apiVersion: v1
kind: Secret
metadata:
    name: gitlab-runner-secret
    namespace: gitlab-runner
type: Opaque
stringData:
    runner-token: ENC[AES256_GCM,data:dMCOjZAw+y0CAP9bNFC68PjBszXeRJIh6vBF4zfwiZAJ7b4MpDizB6WxHZUBQE11C+559t4dY5AAzsKmMpLuJSgji+hiWwW8tw==,iv:/RvVm4d5QwbLT5itwUiKFMRJABRvXR/GCAJn4Qoawv8=,tag:JOzB1mg/g+bihWligC7m3w==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBETkFtZXhSSHMxbERJZmor
            QmtwTHdGZ1p3MEo4VWxEbi94bjI3bm9rR1ZzCjJsbVMzakdOWkk5eDhML1kwWDRM
            NzZKNmx6N1l2SHQxenMrTVFoZGRYcEkKLS0tIGpFQk4vQ2tTdXI2VUswbHR5K3Bm
            ZTVjdmwzNDgxcC9DQ0FBRVN3aFdIN00KpRxndS3lUdjQ7mPvBtQ3CZG9yVn2TlQS
            lcdRIJyt7vcHaMCSF5+qyBCo5XpqN5ceKTkbamCyV/p2d1WfS+5BIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-22T19:49:35Z"
    mac: ENC[AES256_GCM,data:miSN0IR2ts6GroWPXfqLHSbOMJBT6rwWWadgoM4gxivs4VQVsrxqt5LraDGy2Wy+aRcCmoEtoMPyyACz/LuBMvlS4b4UimvDnHHFfCU4pkpHwIko2O92XuwHLKhDWMyNqdhLqS/8Hyr5w4u/VfYu9f1AnS+/7U1nSS1lEW3LgHM=,iv:2r5ZABoPNkdx5IBVo8PRORlemokNE9Y41Y4K8slegjU=,tag:nqO8DHcxI3ABdDUyNS91fw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
