apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  # Core resources
  - cert-manager-namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  - cluster-issuer-letsencrypt.yaml
  - cloudflare-secret.yaml

commonLabels:
  app.kubernetes.io/part-of: cert-manager
  app.kubernetes.io/managed-by: flux 