apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

resources:
  # Core operator installation only
  - cert-manager-namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
  # Configuration moved to separate layer

commonLabels:
  app.kubernetes.io/part-of: cert-manager
  app.kubernetes.io/managed-by: flux 