apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:7QzUtnf8kBZRBZndUlQmMm8PEfd7FoQ4f/hWOwpk9PMF/tX3DKtBNxsqdEqfDHy/+JB4m+6IdUQXrZS8+vsLg3XPrxgrKPnEXUQ1nJ3II3Ypdsu4bQZ5SnNyMitAekviO0W7ze4fgGTXuzb8CjxocGsZiXwfFryLkZstewmkhBZozF81vfvnmBEEyFKdBa0PDJvFCoNb+FGL5+LPDjPWFCd1HlF1KrBD0uF0lWc8g0yARGdba/K/ge/CzKgCVtWIXhs+H//T/LmWL5cqbvY9lv/TMkwFWIL6NDRJBhbs7CRfJ3SjO8HrJvvHaYk5Dc3t3s2ZacCYtkxh2T2pVYV7EQIWUAlG6sN7IR3nvh9mRZeC9FlmSgn88vQ/ewSNlqTYDgGj6FGJ/m0GMBIwszuXTM0hkJ6cXboDeCGsJ0XnCGCdOkIDnazofA==,iv:Q5nLeRWGbM7JgEBsn4Hmvxs+jQ+O50zn7YhY7RLLrNE=,tag:MexQ/N3FE4wPMo0n2Qk6Ig==,type:str]
kind: Secret
metadata:
    name: gitlab-registry-secret
    namespace: app-990prep
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrK3NIYVk0dUVLN1czeUJP
            T09uV091cXNTcVh4TjB4ZXNGMkIyUHNLd0dnCjYwRTlFaVZFQkxMbVFFdnZ0L0Rh
            SDQ3WkowKzhBcWEwYTUrekNnQzNiTWsKLS0tIFRJaXhzTmNhY1hJdldZUmpXWWFu
            M1hnOXZqclVKT1ZoTlJ0OUhqb2hiMnMKQwS6DGX3GyXVX/K1L5ZvAg767Zz+ylwr
            swh1zBM+GbCgkZqGEL+nfTS1hmjMAtB2jnG3/pJ9xxVwFHwCJ3pslA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-15T08:22:08Z"
    mac: ENC[AES256_GCM,data:rtl9nL7JH+CqXlpPmCNcE9xxXZrRx+UBGSw96/C8GLjre7MkYZ70UVndvrUhqBTzqWP+L83k+2zvkoAJlBL/xAObipqEvrDD7usIYfW+ulYWbwEgE+y+/1kiXQR4O02m6Jq3BsorfK3h6Uy+1WtyuanI7rH+0O0AU8bV4+p+20c=,iv:5kVpPfk8dzJZKy0L8gCpS+hV9rNT4lJ/DRCH4SKSlsU=,tag:FaXxAtPPNIYekctAARzThg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
