apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: secret-env
data:
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:TnI6/oS9w1KZYT9huNalgsHp6g62BkmftoCTA/5LFV8AfnFNx2emGtelUL1fWav5CMNuEFWdmVreTIQh+IitChVn/NMzBlEbCqNLcNeqc2kpSEu8ApLsVceyIt+oUKqj88xhCTGEDLf7bXT05Rz+Gwf1d/Ras1QigHvN3XM+X+g5lKlnJUh2UV/WvNc5cD6X,iv:q+EszUN8ptztoAGLADFEtl4YYNJbZZJPkuU3pdn0XGE=,tag:qE0SULG/33XHJHfhf8MPCg==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:wOfqgcNGOGgLjOdnZLOrstTW/7/Em7CvxRhjZ9W3j/IQxuwVi+Jb9vrgstkrgAjEdyjLHA==,iv:NG4xkwTLDJupu+FJRJE/78pDC2KR8XjmiQRx0n7q8Ns=,tag:AZFB+SE/ovglBPGEauWwtw==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQWHVRM1BvaGlIaGlMN3JG
            RGVKSHFrT3g3OElHUHduek54ek1DZ1prYlZRClZtTnlCZjhDVHBpWjVpbTR5RTJx
            MTh0ZDRxU3RsQ1MvcEtTdDE2SDRQMFEKLS0tIFdJM0RHcXMxNGhDdjFuNVpIUk1P
            Q3A4WC9vOG1RQkk5UTRiTko5NWxQU3cK6QxutR0KSivj3soF5nhNh+1dlCqIKRFx
            /ZEr1IXpOXeeB5buOyB1FPlfxb3lI/jeTnd773w6ZApMcicEG/ZY9Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T20:43:15Z"
    mac: ENC[AES256_GCM,data:GgBThUAlWMtn7DygefObQJLw3ybrIXSipycxxjAWa81n8QQaPVE/zIWK7nyPSUjex256yhvqZxiBjoeLsRcRrT0q+65RJcMLj50815+OZuQizR0uy4V2JcNXYmhOEOFrd4JUt2ENL+bapwfc7/pJXTnR2Qf8pMxpYaaAGCrr3j8=,iv:BM1DyabBQ2t7e8d4LNptO9xeaJebPU0D8pb8Y7N+W0k=,tag:UpjAZ/2UgkBx/yxv+7ZSpg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
