apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: secret-env
data:
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:j4KhKW/iryezn4jIS9EBcg3O7tz/6aG2dQVdRmDoAKpU08MKbt+HklLQWw0sEMUOpENVVd1QWi8BErFWgQue6HLwgnbDEmJ9HYdpzquRm2bHbEt33XJxdVioglBRUm3Ny+yEavb4VCyfXVv1ALcONo1/JzyuIDvfCOb/Y+cczxXomAjqeI0kXKS1O5TtLYws,iv:ziasjIRUtsuKDjb5wRsF4RSsouHjDZKZxhFYtUrVbEk=,tag:9ahcY8lf2j8gQ09orcwm9A==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:+NYLL2xdrx+Pgruu1TU2q4QfrdYld9KMO6JOXS1J4mweuvvLTSNA6bER8fY7M+/Tyq1/9g==,iv:91nJelu5ah4mMIfojjDt7Cg1YJ+NbyzQlnBztgip+vo=,tag:qTL3YAy3XK7GTqRA3PDghA==,type:str]
    SUPABASE_SERVICE_ROLE_KEY: ENC[AES256_GCM,data:ZsOVrjaYqZZtTF0C4CR6WZap4mDL4a0FVjWLiLv/2c2jF1pnObEHzsvmWe17KVq9At2DNVQ52cE=,iv:mQma7mjEda8iSJKSDSzNmXNU7iPIcWnkjKwhY8V3W8A=,tag:AjeQqYFYYIpfVBlSCHxSAw==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdUU3NFV4RGZxaFhKU0cy
            WXNaeHNqNUF5eHYzSFlkaFNUbmJ0OHM2T2t3Cnl5WWYyd2tzenQ1Y0dMcTc0QU5u
            bXJKVk81clg3WmZNaXhzV0M4QjdUS2MKLS0tIDdOMU1XbVpoRG5PYzBJTldpRldv
            Vnp5WmgvVmR5clZDT2NHM0hySml6K3MKrtwo5ZV+dnCWsnNDxI6GRqgAYHoQ1Cfc
            OW/oUntD88LxirtaxPv8daUYrKRCg2dty/u8gqFxdM0/SvM6LysOCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T22:32:39Z"
    mac: ENC[AES256_GCM,data:Op0eo9j/MfhADoaGFWf8dbnl9/EjOubAr2y4UZ/BYs0tS2rmn2FIJHDFykPifBZJDMG07f2gKTdZ7QVuaiKGfjRcRzwcwT8CyPKNXSsFgWpe09n17btRQ0mQIFIVsqKbYjQdQHZqVa/RPt6Pzrf/lc8BtP0g5JyK1l71dSIB6MI=,iv:IygttLO8uCsGN9gGGeTn4PlFs5N3t508RSGUpeY6qf0=,tag:HtEUh0gB33c4sCYZCidvhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: gitlab-registry-secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:xEWUs4/53QocGvlvQlfFaKwhVujhi3g9Lm5zlU3lOs2A5X/ftVPKw7EJ9Q39rLTzYhkGn6EtSZ/wLoYBEI6mq34w8qZMOmSeTWIIrSJE4kDNIoPaGR/ZN3Q6krjP/VJtnc6v5mXkl2Ukf9SzjddAcAazVulqUhhkqzbVaXHOr/+rbtGaddsTiMILO/n6mCUYzU32tXosPVnqrOit2wz1Uw6mZCrMcDPhZN6H8F/twRf4gk0wKv89y+BcIv/Ozu8bvREprWR5VUFCef5xm4iHPvpYEwBAP3Afu9uRUEU0BGGTsXKb+6t4kvKAkGHPVHnxeFXoaga5imhoR3Ti9CDxT0pBqlNTXNPKJWW4UCXeOMUrtOisb5MtV9DtKF8VwCLPcwd2QtqHPOJfKStJdmAl3KjYr0i/uuZxiVtRpDjAe20=,iv:qO1g9AG4NxU1N4OmLKgPLGramtdwY+H0Kw8pj8vwMjI=,tag:tqwC/CmArIu8F7ESrIOaHQ==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVdUU3NFV4RGZxaFhKU0cy
            WXNaeHNqNUF5eHYzSFlkaFNUbmJ0OHM2T2t3Cnl5WWYyd2tzenQ1Y0dMcTc0QU5u
            bXJKVk81clg3WmZNaXhzV0M4QjdUS2MKLS0tIDdOMU1XbVpoRG5PYzBJTldpRldv
            Vnp5WmgvVmR5clZDT2NHM0hySml6K3MKrtwo5ZV+dnCWsnNDxI6GRqgAYHoQ1Cfc
            OW/oUntD88LxirtaxPv8daUYrKRCg2dty/u8gqFxdM0/SvM6LysOCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-15T22:32:39Z"
    mac: ENC[AES256_GCM,data:Op0eo9j/MfhADoaGFWf8dbnl9/EjOubAr2y4UZ/BYs0tS2rmn2FIJHDFykPifBZJDMG07f2gKTdZ7QVuaiKGfjRcRzwcwT8CyPKNXSsFgWpe09n17btRQ0mQIFIVsqKbYjQdQHZqVa/RPt6Pzrf/lc8BtP0g5JyK1l71dSIB6MI=,iv:IygttLO8uCsGN9gGGeTn4PlFs5N3t508RSGUpeY6qf0=,tag:HtEUh0gB33c4sCYZCidvhw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
