apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: secret-env
data:
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:0F2DYm+JLkuDan34WdzMQ/ikCVpOsRs/acsOKEjW3DpNARR7pV2Iozuzp9XJjVkSAuiuce5EYbE+lgePuKnfGUgncauD5BuWvu2nom4S0k8HYWhOhHQ3uL4d6mX6ABhTVZMNF38mGJysE0G14U6abnhrZW2yMKzJg3dQvi1bCqV4/FuQ9dQgcHV8EQnDQvhT,iv:M/Z+ioJygLB06g6cTxbc9HVfKYUri8PjS7zc8qM+WzE=,tag:oLJm8vRMu4Vn8D6+oRxwPA==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:aGuuKGfAU8qs0bdpPZuQiSji/O3Ws00zLDvhWzJUS6Uy2z9Pv6Xl15FULZ24xenTAC/6Xw==,iv:spMicjBc7pespX44aMAVmggALfqhbFfv12afYx2hP4E=,tag:W/UHLTmJjWMP5Fba+ba8Ig==,type:str]
    SUPABASE_SERVICE_ROLE_KEY: ENC[AES256_GCM,data:BGLLgD8qTgy/PM++FoSlw2sBC2NlStAWt9Ous0+oV79oikLm9uAp0Q7zPFire8ihtcwWjMnlNptEYEPW2L6xJipDoJvIX05Wtd3ydg+Vf84i+Qf0y2Js/LwnPgnxfAE3a/vhuNJJD+g8esV1+0bbsoQUUz56MQOnVU+dHxm/Wmzz226R+IwZZ7uUYfPlTFE+BNzAgBvInuNH637qoLRY/dy+SHEvgnXM5WsP/zdVJPsXCFBHj/n+uLgs3C1EzjUHa9AjC2wEJwXW5let2AedauAQKq+slXr3Wy04cUXwHIegFjmKN0b0urNTJ/BT/bcm6VWbGbF2CC7h5AOdyxSa1hY+habELCHl8MJkXkwxHLp1Cw+ICCqL/fqJ/ZBGYmfMYc3qwA==,iv:FCfEzpvFLpS9PixyXRRxgX70pPe1cTCZOMcLC26ZjgI=,tag:uq1JYdgertNy1T0m8pHKYQ==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENlhXV2xERCtaYWpLY3dt
            dHMvNVcrRDdJVWZXeGh4N0Z4QXhHUEFEa24wCkl2NS9raXQwdDlBOWJyTDJIaGpS
            UHJnVHUwaStYcEhpVDVpU2w2RGtIdjAKLS0tIEh5QktnaHl0ekxEd1RMREZnT3lK
            cURTSjZOVzNGc3g5ekNLcE1kaVBNVnMKK0aSO4DSDMUVYO0ErBhuRJVoNTFV27tw
            dUbLyAy379qC0c2g/m0GWtCcauZvO/6DGS/X5bH+GGDeovRoVpONmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T16:23:54Z"
    mac: ENC[AES256_GCM,data:sM+KBvYCp0zZM0NVAbtQRBFWsKdFfNkVjG35KtSw/dzeFI87QbhMXpvjYGpQSe6N450S7p7YyljQc7JSf8tPRoaA/joFZtOxdc8ReK9e3EzvoifmVRIMxZSyoOpdVzuiUpB0rI1v86/wnqtoxQFKM9gyIaMeGlXPPY+SIodqjrg=,iv:Xpbtnu2WATkYjxiI1FzuOfQtRK/ZGOM3PH2cWxBWYA0=,tag:yf7D0UXu6PD86528i6iR1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
    name: gitlab-registry-secret
data:
    .dockerconfigjson: ENC[AES256_GCM,data:nD0I6h1tn5YVEWEoxGfQrWSfu1tlY5dHh7lquhWcsZLUu777rmAPPQNXEk+9+FzIgGUj2DkR5X5+FQOXOvOeX7Qq6I+IJQxhN2F2Os5KwJJE4etHaQZVjvXLRQ0OfvDBquik9i+mR9gu2eXzmnOnUgCDM09sGcPrCS8tBxphbxx6u2F/0j+iYMPYW/46UXAB1nXC0+ZTxnvOuYLBJ4QzCd9Vr5r/vUFBayKmOGVNJkTf+C5Gf5B6El3hpj+vCdlE5g+vEybtFgHhX0YUsCtKN8ik71lj3ElZqCYLv4s8Iw7YkKYjRjicY3Ml/m+QVmy1Foxt1FnYtP9F2gmM4GD5PDcetDlGp7SOAKjQ7tkUshTBgS8Nj4t3bvcKwfi6LvYtisUYkCS6Zo2t70FC9IXxZka1jRW9SCN1oWnxGbDejoo=,iv:laxemZLn3kXiyRtD0fVw4ocGQYIUm6+AhcAWQUbTckc=,tag:nfEWaQv9dyYexTg2XXC41Q==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENlhXV2xERCtaYWpLY3dt
            dHMvNVcrRDdJVWZXeGh4N0Z4QXhHUEFEa24wCkl2NS9raXQwdDlBOWJyTDJIaGpS
            UHJnVHUwaStYcEhpVDVpU2w2RGtIdjAKLS0tIEh5QktnaHl0ekxEd1RMREZnT3lK
            cURTSjZOVzNGc3g5ekNLcE1kaVBNVnMKK0aSO4DSDMUVYO0ErBhuRJVoNTFV27tw
            dUbLyAy379qC0c2g/m0GWtCcauZvO/6DGS/X5bH+GGDeovRoVpONmg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-06T16:23:54Z"
    mac: ENC[AES256_GCM,data:sM+KBvYCp0zZM0NVAbtQRBFWsKdFfNkVjG35KtSw/dzeFI87QbhMXpvjYGpQSe6N450S7p7YyljQc7JSf8tPRoaA/joFZtOxdc8ReK9e3EzvoifmVRIMxZSyoOpdVzuiUpB0rI1v86/wnqtoxQFKM9gyIaMeGlXPPY+SIodqjrg=,iv:Xpbtnu2WATkYjxiI1FzuOfQtRK/ZGOM3PH2cWxBWYA0=,tag:yf7D0UXu6PD86528i6iR1Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
