apiVersion: v1
kind: Service
metadata:
  name: jackett
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: jackett
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.6 
  selector:
    app: jackett
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9117
