apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: media
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  loadBalancerIP: 192.168.1.2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8096
