apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: qbittorrent
spec:
  selector:
    app: qbittorrentvpn
  type: LoadBalancer
  loadBalancerIP: 192.168.1.7
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
