apiVersion: v1
kind: Service
metadata:
  name: radarr
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: radarr
spec:
  selector:
    app: radarr
  type: LoadBalancer
  loadBalancerIP: 192.168.1.4
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7878
