apiVersion: v1
kind: Service
metadata:
  name: sonarr
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: sonarr
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.1.5 # change si cette IP est prise
  selector:
    app: sonarr
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8989
