apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:8uVQHjremqCkmeNqs5hdq/et9LemgSgIkndCIiAMLySDnnAR6Weafw==,iv:RJtupdAZEDYueoE6e3buts7mMosa+vnPDQ/80KaFlao=,tag:gX4G1x80//fZsRzyhMX9uw==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeHFURUJkUWNWQlRIZVpU
            Um85ejVXSW5PeWFJNndpYjlvb2dVV3luWG5jCkgrMDMyS3VjTTg0cW9sWG9tU1Zq
            QzUrSGlwYWcvZFNpREptaVNXb3JNQWsKLS0tIG9qQjJQYS9Ob2RMcUNtYTRwWWs5
            YzJLclZTRjVjdzJ3VDhPUzQ2K1orOVUK1TRiRvJOVwDRxsnr9Jr34hDnS7IKPI8S
            EOXFWC3e+Feetofuqq4Ch8l/UJqXePqSzhiamFvrpf1AZwmAs/XKZg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-26T20:17:51Z"
    mac: ENC[AES256_GCM,data:cbagasvezUj6SQZb+JhvlppRk5RO2AdAU5D0/rDxf89VUwn8K40zXpT7f+TABvxQwiKOjuqUZh6H2pWKX16sngp1j2y2LafxgNzsPZXXaDSUggIGM0I8SfwF1s6KkyWkCu8xwAf7tFUoGoOvd9sGgWL9PLZwnH7+u4EpjJ05N0w=,iv:fcsR5bMkh1YoDLOy93GxIjVmWdv4tu3w7COzBYDOg+0=,tag:xV5JEdkVYWQWUg2f/R2I0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
