apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: longhorn-system
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:ttLWzS/hS7/3gv3xfPlVJV5YZG+9YCmVQu7JSs/t8qjlUOlFwYm3bA==,iv:8kfL0a3cw6FZFX8T9aQ5CUcuOjLoZaSNrgYRWJSdxGE=,tag:qeD7/w97csTjY//6xfxJ5A==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YzZhQW80dG4zS1VaTGln
            Ym9Yd1R0bmMzWVhTQko3Ykhzc1ZaZlgrTVdVCk16YWZvdzloVEF3dHNveUsvVk4z
            QWFJSGZFYWxodVJhVmxjR1VGSDg0VWcKLS0tIFE5Y3hHQld2Ry9WRkpINDNwTm9k
            NjVPc3UvQUhpTUJ4NDZwOTM0QjNycVEKDN1YmrNBHgeYbZd7/4Kv8bJrDIaLiewe
            DhE4Bf2rsr49TnVyhast0Hw7Ba+CcFEv/zn4x9s10rUxEndKTFnYyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T19:43:06Z"
    mac: ENC[AES256_GCM,data:OgcxfgFFSyMXRGL9PSlYCmCx3Mmq02pyNLhw5P6o3tonbUACQAKNh4tVoFBe+aVMeGyfnvn2tArqmfUkp4rutSpFruPmbL4V2z3SzLeYkOFvWsbkc3H6J/u0OPnTMqhtF5K8Xt+qsxKUD257ooAvb9k9UpL6ptCIy/PZGu6FKqI=,iv:4rZQTveDyC/vMofRkxDKNLaDRmP2dPw4YA1Odesjpfk=,tag:jQ+I9kJK1rOsy7PrVhwI3Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2 