apiVersion: v1
kind: Secret
metadata:
    name: pgadmin-credentials
    namespace: pgadmin
type: Opaque
stringData:
    PGADMIN_DEFAULT_EMAIL: ENC[AES256_GCM,data:s92294+jg/94E4E5bZF/,iv:4xtA3ec4ETrlovxxX1nj1Ivn68K0e+hiHot0wQZXQuA=,tag:MEwk9Q6YctUx1YZ0koDQEw==,type:str]
    PGADMIN_DEFAULT_PASSWORD: ENC[AES256_GCM,data:WbFBDbwcKcqBDVDvvQA=,iv:L+Y45fK+u34EksgX3FUhv0S6BKZYF9G5I7faho7rn30=,tag:yjNv/lRXHTCwVdP9mbcyJg==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcGtJc0RoUmJ6RWJ3TkFE
            bUU4UGdGRnlZVjYxVWdYYllJTVg0Q1RWNmpnCmZRcDl6blI3bVhNK3F4SmQ3UVMz
            NUxnclpILzVITFFFY05RSFEvbGlqNGsKLS0tIHMyeEsrVVRrQUt4azJacFNZMlYv
            dVZIV0syTW1qREFpa2VoY2J6ZWMyYU0KDQI+vTG+akLz/X2fe7fohvI7yTYUrT+P
            YkN5KCdLmahDoZAW70eb5wwOrsLAr6sJsalx0ZtFtYzGbo4aTcnjBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-28T19:09:32Z"
    mac: ENC[AES256_GCM,data:3UALThKbgUq0LbUMn0PmnH0wRi+K0kMUdFMlenOFiyoMukpiPnP3z1tFCvBzd00LRy3NNERGtWvkJ8phoMkoCGyc7amwRqzBaOYCXmINECK53MLbj2H4n1Njq5tJhxU2WroRClNiG3mBRdDBni0B15Ij/ixUv4lZzJT1Tw61X8A=,iv:IkFk6s8EJnWQx80lZHKhtPmhTcrO+W52pWdIElLtsms=,tag:D02XQLUegEaY+U3gp4SfPg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
