apiVersion: v1
kind: Secret
metadata:
    name: nocodb-credentials
    namespace: nocodb
type: Opaque
stringData:
    NC_AUTH_JWT_SECRET: ENC[AES256_GCM,data:nLlixz21U+2UeghYejkGlDgXVNJLzppcN/pVnb4OguKiI/gAEmTfmO0AF6zguJoh/2BS9y2ebvJx4hK7atmqqg==,iv:jax5ASsJEnyG7m1fSimDSGc6M4gq0pdirUMY1u7Df3c=,tag:YwZb+BEqQ5bpqD2iWazb+A==,type:str]
    NC_ADMIN_EMAIL: ENC[AES256_GCM,data:BfDP8cIhnio6dp5nNNgzfO5zgmbc,iv:9VxLtNLNM2L1lDu2Vr9H6IRktCN0zh4RLpGAU0FzgxM=,tag:MoucOu3MbAwZvoez3jUKbw==,type:str]
    NC_ADMIN_PASSWORD: ENC[AES256_GCM,data:BqwDw+QaR7PtUeyYP35I+BIOf++r1g69,iv:e/SQcAxAnPO1G9jYwfLIsnqWJn1CYqM43gvPyFcQWbQ=,tag:yT6Hfcwiw+o1R5z8NfyXQw==,type:str]
    NC_SMTP_USERNAME: ENC[AES256_GCM,data:LTdx0fRvJnuf0wpN4NQol5Tq1V4XJmDe,iv:q1nCXAyHMtD+5ASVyo0KS1vhM94WGcwad45TNwxpsdU=,tag:uppy4LPZB9hIp+csJf416A==,type:str]
    NC_SMTP_PASSWORD: ENC[AES256_GCM,data:2FA2QUNLNNNOrxI5tWPs+zaijTenmDpAec0a+qo8xS0tmlWnCVYLBvKDsBWudESVDzEowd2iaD9lBcBW+uqIxsMZeTbt8vaUWGKavj6B/myV23j2moaF8Fe6,iv:2VHC4uvqdZ1/FbXBbjKy0U3H9LQpaH/bKpv08OkleV4=,tag:OAOMu7Ry4JrvldXFdIN21A==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvRzlYSm9OZnhjSmNQMnJB
            dkVCVWdoT0VMZHM3K0IyTmkvUXhVdVoyYUdVCmtFMjdGNEZlRHRKbGw3VXZic1Bj
            Z1dycHhmNW1BL20vdzBsSFo1d0xtMVkKLS0tIFNKTkQzOWhEUlJXMGw3SEQ2YjJB
            TWhnSUF0MC9DSm1NRzBGYUUyT05XczAKaKehrSiaUMD3IYfM6b1XR6ff+L6LiQ2N
            NchfYUj6TGl0yEK3UHcApMvtWn5YICtbaDk02y+MKPGtfQPxEluJBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T14:36:43Z"
    mac: ENC[AES256_GCM,data:Xy5XZGEOsldytIW9NvPpqg+WxIDSha3ZjmyftC5LAox2VofzrPAYFmw0TZVqBPK2ombpiePxyKRnihlCg+J+ZMIdoNJJF3/Snp4tJmKTtPYaMymeX+juS/PyXvCFoGRk4cwDzku5K/bWXbjb4wAyUPt2sSpBzF/n7W5lF3FI9C4=,iv:jPQiwBeMtAgstiIdKS+ZDs9keNB10t4TUpoo6B1ze4Y=,tag:8iRNoLpub9UIUiC0B89y2A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
