apiVersion: v1
kind: ConfigMap
metadata:
  name: calcom-configmap
data:
  NEXTAUTH_URL: "https://calendar.justindesio.com"
  NEXT_PUBLIC_WEBAPP_URL: "https://calendar.justindesio.com"
  NEXT_PUBLIC_LICENSE_CONSENT: "agree"
  CALCOM_TELEMETRY_DISABLED: "1"
