apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nocodb-data-pvc
spec:
  resources:
    requests:
      storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
