apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nocodb-daily-backup
  namespace: nocodb
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: nocodb-database
