apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana-loadbalancer
  namespace: monitoring
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  # root traffic to every pod with those tow label
  selector:
    app.kubernetes.io/instance: prom-stack
    app.kubernetes.io/name: grafana
  type: LoadBalancer
  loadBalancerIP: 192.168.1.1