apiVersion: v1
kind: Service
metadata:
  name: linkding
  namespace: media
spec:
  selector:
    app: linkding
  type: LoadBalancer
  loadBalancerIP: 192.168.1.1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090