apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: "6.6.10"
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: nextcloud
      interval: 12h
  values:
    nextcloud:
      host: cloud.justindesio.com
      existingSecret:
        enabled: true
        secretName: nextcloud-admin
        usernameKey: username
        passwordKey: password
      # Configure reverse proxy settings for security
      configs:
        trusted_proxies.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_domains' => array(
              'cloud.justindesio.com',
            ),
            'trusted_proxies' => array(
              '10.0.0.0/8',     # Internal cluster network
              '172.16.0.0/12',  # Internal cluster network  
              '192.168.0.0/16', # Internal cluster network
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
            'overwriteprotocol' => 'https',
            'overwrite.cli.url' => 'https://cloud.justindesio.com',
            'maintenance_window_start' => 2,
          );
    
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls:
        - hosts:
          - cloud.justindesio.com
          secretName: nextcloud-tls
      hosts:
        - host: cloud.justindesio.com
          paths:
            - path: /
              pathType: Prefix
    
    internalDatabase:
      enabled: false
    
    # Configure external database connection
    externalDatabase:
      enabled: true
      type: postgresql
      host: nextcloud-database-rw
      database: app
      existingSecret:
        secretName: nextcloud-database-app
        usernameKey: user
        passwordKey: password

    # Storage
    persistence:
      storageClass: nfs-client
      enabled: true
      size: 200Gi