apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-backup
  namespace: nextcloud
spec:
  schedule: "0 1 * * 1"
  backupOwnerReference: self
  cluster:
    name: nextcloud-database