apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: nextcloud-backup
  namespace: nextcloud
spec:
  schedule: "0 0 3 * * *"  # Daily at 3 AM 
  backupOwnerReference: self
  cluster:
    name: nextcloud-database 