apiVersion: v1
kind: Secret
metadata:
    name: n8n-smtp
    namespace: n8n
type: Opaque
stringData:
    N8N_SMTP_USER: ENC[AES256_GCM,data:Cg4ua5Ep838IxZvTfbbIBOP5sNFYpstv,iv:2tdXks3+8fpkH9r/ztmYBYewNiZ0OrX4kZnmpoGLAOA=,tag:fkgztXBajp7mAZ0UXphkZQ==,type:str]
    N8N_SMTP_PASS: ENC[AES256_GCM,data:YXhpTQs+KdxG7uyBWHZE9Pt+6SEs5YzO0KAVQqTfuEOEsuQ+QYLijVm3uNDggmtZNnGWXBbvvymmdeRFSQKf+ry2erUuP+Lp3O87GKmzHj1txdpCtzU2pTa0,iv:Dg1Eb2kO4t4lakt1u5WJDswub9LF79tbroFFNDGJwPA=,tag:Hyp6WDuJ+6UqAWywPmDFHg==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2dXRZeXVPWjA0SGNvalhG
            UFdMVzl0R3pEenVrQmFjVUFhdk1WdTA2OUdRCjdEYkhKdE0xT1FUOWRVKzlTM2k3
            Q2VEamtsRm9aTGhMUlBYWTg4SzR2RTQKLS0tIGp2UG81bUFHK1pQc1RjU0g2aTUz
            Z0dVWWdmb0x1N2lhSzJ1OFE3dnRueFUK1rraklcTeNSeBNSMPeQgKdoneWt8nwIo
            PVL3AsKBT7VCAu7ZqV1s9G7tpZizRh57DR5nFdwy1lbvU2Pjqgqjig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-23T17:13:18Z"
    mac: ENC[AES256_GCM,data:MpEjC7Wd5OzbxeXbMiB94/oo3+cGaxcmWkvqVNgYNITFQh1BaFzC6QKSMt2Yl2qp7Dy+CsX79fEeQ/Cnx5qENEI9ZCPE/mE3ECqBMCSF6zOf0yYP6Yf7fSLJVh3UaqqQSGVMrBhWeyyN3hkLpg32N6mX/F/ZUAS/53al4w6/Tqw=,iv:/HLey00ECZH6dkdd8bp8z+ooOOfsLXP9pxsDJinZPDQ=,tag:P5xR6qHchG9wO5IbX4Qdvg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
