apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key-secret
    namespace: longhorn-system
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:fub/EXyOqtKlrUauzE3XP66wDBI2t+LxKjgaCvfVTj1mOLMQOUfZOA==,iv:zL2pJOOK8TsqrihsSKaGMSDzqBCPU1ix/qnSCvU8Amo=,tag:sDXp9vUCEoc3GZbBk/1clA==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YzZhQW80dG4zS1VaTGln
            Ym9Yd1R0bmMzWVhTQko3Ykhzc1ZaZlgrTVdVCk16YWZvdzloVEF3dHNveUsvVk4z
            QWFJSGZFYWxodVJhVmxjR1VGSDg0VWcKLS0tIFE5Y3hHQld2Ry9WRkpINDNwTm9k
            NjVPc3UvQUhpTUJ4NDZwOTM0QjNycVEKDN1YmrNBHgeYbZd7/4Kv8bJrDIaLiewe
            DhE4Bf2rsr49TnVyhast0Hw7Ba+CcFEv/zn4x9s10rUxEndKTFnYyQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-29T19:40:29Z"
    mac: ENC[AES256_GCM,data:i+3uw/ydWubmjAWkAYomaJ66B7IoKxC9na6d3rXG60rNYMRwA40l34jzQjz/LSpJ0VmFNkwLnWEOviVpOuMCMKE/pORejC221AUr06JiHwErE+H72wLggsaD0Rjj2OsXeYv4xBImhOcFZmwbxffQnvu0j+9xQCtWoz39Z1KRCTY=,iv:EItmQoLK+ywtvKtXukmTL7efZ6t4SK0WR/g77UO6BiU=,tag:VKwV3qbVHu8YJBLJqlEL8w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
