---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  interval: 1m0s
  values:
    persistence:
      defaultClass: longhorn
      defaultClassReplicaCount: 2
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.justindesio.com

      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      tls: true
      tlsSecret: longhorn-tls
