---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn-release
  namespace: longhorn-system
spec:
  values:
    persistence:
      # Set to 1 replica to avoid write amplification with CloudNativePG
      # CloudNativePG provides resiliency through PostgreSQL clustering
      defaultClassReplicaCount: 1
      defaultClass: true
    ingress:
      enabled: true
      ingressClassName: traefik
      host: longhorn.justindesio.com
