---
apiVersion: longhorn.io/v1beta2  # yamllint disable-line
kind: Node
metadata:
  name: homelab1
  namespace: longhorn-system
spec:
  disks:
    ssd1:
      path: /mnt/ssd1
      tags:
        - ssd
        - performance
    hdd1:
      path: /mnt/hdd1
      tags:
        - hdd
        - capacity
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-performance
provisioner: driver.longhorn.io
parameters:
  diskSelector: "ssd,performance"
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-capacity
provisioner: driver.longhorn.io
parameters:
  diskSelector: "hdd,capacity"