# NZBGet - Usenet Client
---
# NZBGet PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nzbget-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nzbget
  namespace: media
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nzbget
  template:
    metadata:
      labels:
        app: nzbget
    spec:
      containers:
        - name: nzbget
          image: linuxserver/nzbget:latest
          ports:
            - containerPort: 6789
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "Europe/Paris"
          envFrom:
            - secretRef:
                name: nzbget-credentials
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: nzbget-config
        - name: downloads
          persistentVolumeClaim:
            claimName: media-downloads
---
apiVersion: v1
kind: Service
metadata:
  name: nzbget
  namespace: media
spec:
  type: ClusterIP
  selector:
    app: nzbget
  ports:
    - name: web
      protocol: TCP
      port: 80
      targetPort: 6789
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nzbget
  namespace: media
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - nzbget.justindesio.com
    secretName: nzbget-tls
  rules:
    - host: nzbget.justindesio.com
      http:
        paths:
          - backend:
              service:
                name: nzbget
                port:
                  number: 80
            path: /
            pathType: Prefix 