apiVersion: v1
kind: Secret
metadata:
    name: nzbget-credentials
    namespace: media
type: Opaque
stringData:
    NZBGET_USER: ENC[AES256_GCM,data:wstDng==,iv:gkoxRuOt0SaVLGsXnHDdLHP8WYiY3FZXZZBkE6nsmQA=,tag:SusiAhNdayJprvgMKu99sQ==,type:str]
    NZBGET_PASS: ENC[AES256_GCM,data:H0sXaWAL7coi3eSZJ56QlKs=,iv:u/rv9QKCjP2xp24DAVi2foHLw3qnnWX6K6z7dZfJ7Vs=,tag:m5dw4Z94RP07a2Ya+G6LWw==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrNE4xU3FoQ2dtY2RqMHpN
            R0lQakdlOXRFQURTV2ZLV1pTemxjTDFqeURFCnYzNSs2N1FkS2hueFJhbDFjRUl4
            cGNadWhXL3hwemkxTGlLMFVMbjJVTTgKLS0tIEpBOCs3OW9kTkxBYUFVajBnbjNZ
            Z0crS3hxQmlMazl6a2VZOFFkWE00bXMKktZdauhEx3Dn5kH8To+wunri5DXum5wL
            v1TSZlRgKxMoGzfa7RhtSk2QeuWDEgYucT2IRfO1/3Gkstbgfnw1ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-05-30T08:51:48Z"
    mac: ENC[AES256_GCM,data:t0BaAidb8E0WsUbKMZ9IDkokywLPT20CsZkajE7jmQETOcZitcEqWFsPQGAcMCRBkjzgJl+5y1I2tqIIwCoScbHXn90ytNXNZ9PKMWhgGoN+SnQLQ4OA3u6jGSQnDVyWvBBHjzC3MhuTZfE1YcNkwe8RgPZeN2w9LY+fwiHBHL8=,iv:UvjuFjuvu+d19EKjUbj9+4SrD/xLglwwFiLE10Tcpzw=,tag:N1kYO+N7gquAzt9PyLWKMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
