---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cnpg-namespace.yaml
  - helmrepo.yaml
  - helmrelease.yaml
commonLabels:
  app.kubernetes.io/name: cloudnative-pg
  app.kubernetes.io/component: operator
  app.kubernetes.io/part-of: infrastructure 