apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: chatwoot-daily-backup
  namespace: chatwoot
spec:
  schedule: "0 0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: chatwoot-database
