apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: pgadmin
spec:
  interval: 30m
  chart:
    spec:
      chart: pgadmin4
      version: "1.30.0"
      sourceRef:
        kind: HelmRepository
        name: pgadmin
        namespace: pgadmin
      interval: 12h
  values:
    envFrom:
      - secretRef:
          name: pgadmin-credentials
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
      hosts:
        - host: pgadmin.justindesio.com
          paths:
            - path: /
              pathType: Prefix
    persistence:
      enabled: true
      size: 1Gi 