apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-redis-auth
    namespace: chatwoot
stringData:
    password: ENC[AES256_GCM,data:nDx5F6/uGllTWpimnYTbj1m0fBlOAsRsenrhr3/oHq9LMHUQ8Zd32eigu8crfrxc,iv:PIGstKvynoYSVNFBaS636Dm/XOsc8nxYIwntGHNa3+U=,tag:HrTEeMOcoa5W72iSCb1mBQ==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOb0NJbjJuSWtRcFdYYzMv
            bUMwbU5VbE9DOU13dlBoaWxqR2Z6YkxBSm5NCmdtYlRCeHJwWWk4a1FzM2FZS3Y5
            K2tkUUVTTlN4Q0Y4V1FkdHJLVkQ4QjgKLS0tIGwxRFFheSsyTGVkQ0dGLytqT0o0
            THpxc2cyYXZKTTB4UnMvYVZXc0RNdVkKtZ6r9ovBuSvKdfb+YjOmZCJDzVMr/Lzd
            5dK0KSjJvofqJMf18oUDqyBBZedRmtPAfz5ayrH9ybI0GEHMwNBl+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T17:33:43Z"
    mac: ENC[AES256_GCM,data:F+TdnW32nuEWjut1KfTtP5oimO20aQNJsIOz3Q5AVNO3LAjIQARwtwSCMDn62g/OeRNT0yHa3DAg+jDb9X4do5aOVg4k1sB3iaoLHrxPCv5eVrRP7qQKZBduc6zl4AsDIvWwlcDf4/AOLhJw0fvkOcjb+bBJihdP9xMI79r75+c=,iv:Qfha8gfuLAUofxMPRGRvAyxnhi+WzjpmVSkmsbiGX6g=,tag:Z+xNKfDMNkxEy6bbmOmR4w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
