apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-secret
    namespace: chatwoot
stringData:
    SECRET_KEY_BASE: ENC[AES256_GCM,data:tg5S5coseSIMmIapF9jcV8L0GZ43LdIFU/OLqAq6W45QSoNXa1k8CcogPUgnobEnyMLAilqaRk/3sFdkT/3LsGzOf1pKmgv8O9La0G5EapyBJ0QlHPYFZJqFE+sHLCVwVvwXfDsyYDuLIMU7RadNO5n+31wnk1CcE7SN0fVICss=,iv:kLdDy7+oLFir67vGy8yAoAb1lvFJ/cYj0Sd8tfIH3xs=,tag:8JwSnWiFHlXXj6Wqy0SW8A==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaktoRHJuMU1DNFlZVUNO
            N3VqZnRSOEZPN1pka2cvVU1FczRCM3JVKzFRCnlkRXJYYmRoRGpvQnNkdVo1T0Ji
            cUJqVWo5RHlwZGlUVk1ZQng0VW9mT0EKLS0tIGM0ZHJlMFJhMHFKb2NNL3ZKL3pn
            WmxyZ3d6cm54TUtRMjkrQUdGTFpaa2cKl3AgWNBCBXH0LhnAhXpkD8BRbzmy/ZG3
            Ud0zRQAwt4sLZgrBstwIU3nss+2b5XIR8ps/nH/ikmBLEU62NI974g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T17:58:46Z"
    mac: ENC[AES256_GCM,data:diXTMTJEwDT01xcYtDVAQwn8hCd64SLvZ9ew+vhdr5AVD/SZNYZHnd5YgJeZdKqz/Sh92Xw+Ar1G31dNnBXS2cvDijKqeQ89Ob9yY18lV319XnmI2lDCOcr9JoySbwe+wfxrH0e1U8h3xT5cBW8RijAztXEj8WaOQlpBzhlh7qk=,iv:y9S8lBOEY/kTsG0qCvfsh+DPvTY6v00maWKPRyx8VL0=,tag:tQmrBsSKI7h8/FUia+fOvQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
