apiVersion: v1
kind: Secret
metadata:
    name: chatwoot-smtp
    namespace: chatwoot
stringData:
    username: ENC[AES256_GCM,data:wMH87R7Zkk2ED7K1/vtFPHtGMwvwFO1R,iv:WsaNSPbb55d8G3TEB7eo4dC8OZJYDQH/UoFuUpkoK4M=,tag:6QRJA/uFKIad3yAU8iUGuw==,type:str]
    password: ENC[AES256_GCM,data:Qub/M1FR4J8CkIzfOLoZhrfyY55GEVjPxZcNzsiGS8cd0f7RUW6qOA1tYmlAFvsa2By7C/kdLDC6HE0XNpXH2XJgEGLh2rAROFcL2mpJaXX6tEj14m+yyvxS,iv:V0WJYh5+G0W5Zk9DuF00CDUJ+jR0K05ANHoX3k1H1Tg=,tag:450uMEc6NY/zq+8P+RZJvA==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJS0RVZlRxSmp3cnVWWVRm
            NGVMb0cvaWlrMlBLb2JUdHo3WFo4Y3owMUNNCk9lYWwyTGkvQ0RrY3dqZGpRMzB0
            dnd0WWF5Z3VEUExJNW9pMWNFRktqcjAKLS0tIDdReWJEQ2dUbXBvVUdiZ2lnR28r
            czJIS2o2dGEzTzhOWmcvVzlyRDJ5L0kK0xE6AzzCHYNSNiAoXzeFES9vCZra6CjE
            TgGxYHijtr/8ADCpdqFWqMu9V266cTnRRBCXyIcwLBdLLoO00XNm+g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-30T22:56:53Z"
    mac: ENC[AES256_GCM,data:DBvZBclPQd8NBFwtuKgW/M2Uc8ULH8WhEaiaj6aI99zU8tLVgYIwJg/ze/Umzd2ItcKzVjBOKE+WggaPJejdCPpmb8NkYz5s9BjyavjycLxQS+VF0oeMX5Ni5S/jYQF0QZxb/atU/oNLnm0I/K3laZLOcbnjfJ038X9a+SyHTSo=,iv:YyQ994tZBfpgDOle9x6fuehslvvTHP1nt/HpoeVMJKo=,tag:qIPFFh/CRDujl4sQJFYeYw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
