apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stirling-pdf
  namespace: stirling-pdf
spec:
  interval: 30m
  chart:
    spec:
      chart: stirling-pdf-chart
      version: "3.0.0"
      sourceRef:
        kind: HelmRepository
        name: stirling-pdf
        namespace: stirling-pdf
      interval: 12h
  values:
    envsFrom:
      - secretRef:
          name: stirling-pdf-credentials
    probes:
      liveness:
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 5
      readiness:
        initialDelaySeconds: 60
        periodSeconds: 10
        failureThreshold: 5
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
    service:
      type: ClusterIP
      externalPort: 8080
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "1000m"
    ingress:
      enabled: true
      className: "traefik"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt-prod"
      hosts:
        - host: pdf.justindesio.com
          paths:
            - path: /
              pathType: Prefix
      tls:
        - hosts:
            - pdf.justindesio.com
          secretName: stirling-pdf-tls
