apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: linkding-database
  namespace: linkding
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:16.1
  instances: 1

  primaryUpdateStrategy: unsupervised

  monitoring:
    enablePodMonitor: true

  backup:
    barmanObjectStore:
      destinationPath: s3://cloudnativepg-homelab-backup/linkding-database
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cloudnativepg-backup-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnativepg-backup-secret
          key: ACCESS_SECRET_KEY
      wal:
        archiveTimeout: "10m"  # Archive WAL files every 10 minutes 
    retentionPolicy: "30d"

  storage:
    size: 1Gi
    storageClass: longhorn-postgres

  # CloudNativePG affinity configuration to ensure instances are distributed across different nodes
  # This works with Longhorn strict-local data locality for optimal storage performance
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required
  