apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
spec:
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      securityContext:
        fsGroup: 33
        runAsUser: 33
        runAsGroup: 33
      containers:
        - name: linkding
          image: sissbruecker/linkding:1.40.0
          resources:
            requests:
              memory: "640Mi"
              cpu: "250m"
            limits:
              memory: "1280Mi"
              cpu: "500m"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: linkding-data
              mountPath: /etc/linkding/data
          envFrom:
            - secretRef:
                name: linkding-credentials
            - configMapRef:
                name: linkding-configmap
      volumes:
        - name: linkding-data
          persistentVolumeClaim:
            claimName: linkding-data-pvc
