apiVersion: v1
kind: Secret
metadata:
    name: secret-env
data:
    SUPABASE_SECRET_KEY: ENC[AES256_GCM,data:y5ODlj3Nub46hx3qlWtXtDaet0HjJftBqNtK6Fgl7ozxkRIow2fBIe4337BjB9AiA8lczEm4K28=,iv:5Xy0T1bk7i4XA3Jcbn6Tj7NFVgQsDWCwykW8vW759Ng=,tag:iWNa4ui/ybzEnV1RNled1A==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFSXpIc2xkRGRXV1diTHAx
            T0dOWHk5QjhzTzlJTXFCU3BqeU5mU3NRNEVrCkQvQUpYcmg0K3NNWi9ONy81WWZv
            eEhoNFUvbUJmcXJ6Z1U3eXFQSjd6R1EKLS0tIGVDNlYwOSs5eER2NDBGb20vb0Jr
            RnBIV0g5UDJXckUrS2N4aXFQemFSVlUK7qCKYp0ii1Gbp9OLj1W+PsVecWXbEpgt
            nWlm0bsnBmKjRq5b1BIqNeA1jqZegwvdGLhH9zkgydR3pkJPW13ifg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T20:43:15Z"
    mac: ENC[AES256_GCM,data:VWt1xPLJMdeEVuTpqEtWOAZs9cJTO7R+BbAS/GkLa/IUgzhl/qUreWSb9p2KM4lYGOVRXu8qpNmFXSPGvCk8ZSmmF4Nji199XvXBLfC+YDHZmRGWB7ES1JwTxM6j2tiby06eoezQ3JSOUep4cJAJfH0r3QBe4ULYaposFfGgv0A=,iv:GhusgYfX6iLaIA/epS89DpFTRyeOP6opBGXo6rpw6w8=,tag:90e5AOo6EvVhSwc4PkJy+g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
