apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: secret-env
data:
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:zKrG3Um550vJNlfCuoLn0mBbHsE3hvbDvYro9MQGZqOeisFGWCEkyAJ4iP5k/9aoFrkSAp277aIDgKee+sMjg/uq7XpsKzzg5CZk1y+e81YDtVHOHEXEy/FhP8Hd4YjU8S3ci6e9KAfx5i5DNUrJpefRCUM3XDJ4q2leHxeBGHQTgxmYmbBEDD+DJjwZSk+B,iv:Hg5EvjbyX59bV42h8qNDk3xP5P8+IZPp+mAzk4h1YMI=,tag:cC8TQpDs7t0VWekdOCLyuw==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:uWqXg7db1GnYz+QGG5zA9QFog0G3DCQhZMh97h+75yzmrmSjmLl/3e5fBnqXo3VEaFvtBg==,iv:SGPfILsvstj383Ex7vwwv0KvGomh1U8yp2AgYBXju7w=,tag:raNvAUc5r11pLQD7KLyfFA==,type:str]
    SUPABASE_SECRET_KEY: ENC[AES256_GCM,data:Fv/xgSsaNEY/qNu4fi+auaddITYioVM/5BSjA+loR9Z4CWtQqI3oL2+QLXkqiHXHJqjpjFs/gXU=,iv:A8v3FSuywbLAatsj7fNmMva5Wi1/cda3hP0HqSzIfh4=,tag:NXBHubrMtaiRDToxGix0RA==,type:str]
    REVENUECAT_WEBHOOK_AUTH: ENC[AES256_GCM,data:dUTXPOWMxfV12nDiV0+5G21tisgwHLfmuA5r3/PCcsRfmWpWm7E1Q016QAIO9sbJbwUUvs9QSwxL/QQKliT+4jHLo1w=,iv:jyBotqXBN4Ail5WVGoO/HtpPqoSZIoshQ01Cd+bs83E=,tag:OpgWi+lFXKZMT5t3SgkRrA==,type:str]
    CHATWOOT_HMAC_TOKEN: ENC[AES256_GCM,data:93u2wmabilqlO5SQoohh3oYs4yk9ThK6as3KHBB8iCg=,iv:sKzPSCA14oYUQfsCnEtR8A8+he5U/Y0wOz4MeL0MsPg=,tag:5Pcfr/0ADIwG7JRwn/hmcQ==,type:str]
    META_CAPI_ACCESS_TOKEN: ENC[AES256_GCM,data:WbD9Dp3P9Ea1z0W7oeF1qf4qHHyg2GYFDfYG8wLFpwXDilfbwcAgsRaq70HzuxUPXTVMM7cJ9Ag0x26+CHeTszL8FG0pCYi+Bug+M2S3wagTtL69I5imxYlZOXlCR4dy5D6chVDusRKohhRU1eFuYLWYFPhcvjG6GmPu4zlv4RNooReAlsaJrcbHK3wOaeHTecEgZb1X/TAdVopds151ydsy8YyVIKu+SxXMRp3wM+aOO0okEsZY9Qjo9cafxA38iPlDFRc59oE7Wlipj6sc6EXfM0jYtcUoX5yR+Gkqya5//KyPqDURDQmVFwk9F3S2F0DlhQnvgq7bcZ77jHxcYRRBsA6Jlb+l,iv:sxD7cU/fucWdfwPVZON0PbTx5RfK5cK9zHupGMOFgto=,tag:UJHrUkPE+oQ42731Zt2aMw==,type:str]
    OPENAI_CAPI_ACCESS_TOKEN: ENC[AES256_GCM,data:ZOKDIstLDx6aiUioXOhBe6rLOp3qgMIKrJxjfuU+I+CQguvlqyIcq9JPvP18TF9UHTiX/NjrhMUJhvuz+7EDmpVKzo5tiGP0EW/6vXxZ0XelMqxB10zzbPrd5UtJH7rIC0elQ51hBuklH1buRZCMDnir1Qd6n//ZnoS1s46ofnQ2LwRou3Fkd0MCXgWWgkxGzdxh6Gi46nD+8SLLW0g42gtraYpnP9tB8d7peTOq+9CNyIw3Tl480mAB9ZXx+VTHMdsMJ7rSpJzhEA0+B4Nv4ej5pGpDSxvEK7W4XC57TQI=,iv:Ioyfd6U4yjirMON5KK8Er+wTNLui1Agb/3lUeQM+p9M=,tag:qtBMELwY6tdg6flpe1SLrQ==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWXFoMVpZbGROdTY1VW1v
            S053SjcyVkdPbldxL2RFZXEyTisyaEVDNzJJCnhPdENuVUpaWGllaDJ5eVlpZXNX
            WW5HZ2JhL01ONStZQ1pGNW1JSGNYdUEKLS0tIE1JRXBkK1pxODErRmM1dlJnekxI
            VHJqQmwya3RhZUJYZGpMZEhzKzIxc3MKh784Dh7XcwEcj2TeHPBpzwOP+BE+2JQQ
            h1zqu80QrqYmyNRMvQbVkM/rvhSKwu2V417VQLrAXAc9zgBDoYzcmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-02T20:16:33Z"
    mac: ENC[AES256_GCM,data:3vOwBWK8NrVIao43PdafefsV079EdVDhaXmSE0RzfonajedCqDqE5ijG7+e9T4t6/OCDPkKX4uNpRAgGUS2LsIPrCX4w84VJaMMc3VKP3BPIEx+YXoGAHiZLnQzIAinpR+7hKyQjZnp4agkdo2eop6jnxJt7f6PB54f0TDg+NGY=,iv:clEiaHfdOywVK2F2bDF7cd8notHklKB1VTFOfEYCqfw=,tag:/cMwKOQr+DhOZCKOS6adRQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
