apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: secret-env
data:
    STRIPE_SECRET_KEY: ENC[AES256_GCM,data:zKrG3Um550vJNlfCuoLn0mBbHsE3hvbDvYro9MQGZqOeisFGWCEkyAJ4iP5k/9aoFrkSAp277aIDgKee+sMjg/uq7XpsKzzg5CZk1y+e81YDtVHOHEXEy/FhP8Hd4YjU8S3ci6e9KAfx5i5DNUrJpefRCUM3XDJ4q2leHxeBGHQTgxmYmbBEDD+DJjwZSk+B,iv:Hg5EvjbyX59bV42h8qNDk3xP5P8+IZPp+mAzk4h1YMI=,tag:cC8TQpDs7t0VWekdOCLyuw==,type:str]
    STRIPE_WEBHOOK_SECRET: ENC[AES256_GCM,data:uWqXg7db1GnYz+QGG5zA9QFog0G3DCQhZMh97h+75yzmrmSjmLl/3e5fBnqXo3VEaFvtBg==,iv:SGPfILsvstj383Ex7vwwv0KvGomh1U8yp2AgYBXju7w=,tag:raNvAUc5r11pLQD7KLyfFA==,type:str]
    SUPABASE_SECRET_KEY: ENC[AES256_GCM,data:Fv/xgSsaNEY/qNu4fi+auaddITYioVM/5BSjA+loR9Z4CWtQqI3oL2+QLXkqiHXHJqjpjFs/gXU=,iv:A8v3FSuywbLAatsj7fNmMva5Wi1/cda3hP0HqSzIfh4=,tag:NXBHubrMtaiRDToxGix0RA==,type:str]
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkWXFoMVpZbGROdTY1VW1v
            S053SjcyVkdPbldxL2RFZXEyTisyaEVDNzJJCnhPdENuVUpaWGllaDJ5eVlpZXNX
            WW5HZ2JhL01ONStZQ1pGNW1JSGNYdUEKLS0tIE1JRXBkK1pxODErRmM1dlJnekxI
            VHJqQmwya3RhZUJYZGpMZEhzKzIxc3MKh784Dh7XcwEcj2TeHPBpzwOP+BE+2JQQ
            h1zqu80QrqYmyNRMvQbVkM/rvhSKwu2V417VQLrAXAc9zgBDoYzcmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-30T21:58:45Z"
    mac: ENC[AES256_GCM,data:tRirn6ZX8z0jckXWoemv4WpN6y9VVFt3OoVs0M34km8dZep8KpHmDFD3seIOzKTohUYt8Hsp8LO5aW7vAC26gPycCoxwq48BzNi0yvg0eEOEZMqusgLlJ0Et4RDmqiC3ByuRbegI3ViUsIwvV1e070s7WQfoMnT0aGlL0H7Q89I=,iv:wC7lPQy2fYWOHx6ggeh1Uh9PdmELtvUG737BDwwDeYU=,tag:FIz1kmYKdj2Zmx/5JZOgPw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
