apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-database
  namespace: immich
spec:
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.4.0
  instances: 1

  managed:
    roles:
      - name: app
        superuser: true
        login: true

  # Bootstrap to configure VectorChord extension
  bootstrap:
    initdb:
      database: app
      owner: app
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vector";
        - CREATE EXTENSION IF NOT EXISTS "vchord" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;
  backup:
    barmanObjectStore:
      destinationPath: s3://cloudnativepg-homelab-backup/immich-database
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cloudnativepg-backup-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cloudnativepg-backup-secret
          key: ACCESS_SECRET_KEY
    retentionPolicy: "7d"
  
  storage:
    size: 5Gi
    storageClass: longhorn-postgres

  postgresql:
    shared_preload_libraries:
      - "vchord.so"
    parameters:
      archive_timeout: "1h"
      wal_level: "replica"
