apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: immich
resources:
  - namespace.yaml
  - repository.yaml
  - database.yaml
  - release.yaml
  - backup-secret.yaml
  - scheduled-backup.yaml 