apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-database-backup
  namespace: immich
spec:
  schedule: "0 3 * * *"
  backupOwnerReference: self
  cluster:
    name: immich-database
  method: barmanObjectStore
  immediateCheckpoint: true 