apiVersion: v1
data:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:bnz9frAlkbudpoM0v1zjhNkpqWIt2ZF/emLczbv6L5kJuJChnU4bbcDIUuJ66W0vatW/Pjvch8M=,iv:VQgDGlnQ+VLyl6bUaY4rwVHSusHLZyooQ7SbwUBJaXk=,tag:QtBn9FyPmH4hHpC9G39gXA==,type:str]
    DOCKER_REGISTRY_GITLAB_COM_USERNAME: ENC[AES256_GCM,data:1YP5JLkJ5MRbi/pPdw==,iv:hWCVa/s/c/uhTAYLTaxYotMWwCIdqx7/wqmiVHf4MV8=,tag:uX+iwqXwFBvl0t0xr6a5xA==,type:str]
    DOCKER_REGISTRY_GITLAB_COM_PASSWORD: ENC[AES256_GCM,data:W03dFF6aqOp29BaHKFLSb1YF4atmwtNHsgYLtrKJukfHVv2WT3HIQ+NorWN/6DDQ2ZRdnkVSip+X,iv:a1STWp6q/qmCloawqjr9ipl+TjT+b2+q/a8yp6A/x8o=,tag:EhJKVGxDs5DxpXiOQMXGBA==,type:str]
kind: Secret
metadata:
    name: renovate-container-env
sops:
    age:
        - recipient: age18y469g67e9nls8xv9x5xsktqucswj283slf03ye0jyg9k3mh45rqgt20jq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtczAzQzBCVkJ6cjJtVmpY
            T0dmZnY4dWVodDRINDJzZTkvcGRLRTQyNlJvCktubnVEdTFvNHZPRGRZQlpNYXZT
            ZjNJSklhQ1BXc0xuOWlJYm5XbGVTVzQKLS0tIGlGRzRiUHo1NWxEZ05BM1pPQ3FO
            TG14dERDTlNxNzJNRU5JQWl0L2QySmcKngB3Ay+LPsw8eqhOKWTGqRpzyA0l6ocV
            ge93gvT+CQtiXwzOEOQuVQ36NCGaI53Q/W66v9zSwVGthim61Nbz0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-16T17:47:03Z"
    mac: ENC[AES256_GCM,data:qBYXrLFaYwn8OS58elF1ShPUXnHFp1k9WaY3PyRbXmwedQVTpIMQoCnYEIMOiUBp2QYN0e93JWly+W9v1+6KxZ3tshigxxvnNbAC2Ss56HjH/fueZRAfkOwMvtpf8NaYSKrUDO8lg/wGJpXudlsRpAXHWXpf9VgX+9U2FYvOn0o=,iv:pFL6/W89XtasXxEwEuSx6qlCklLH1cPtPUikn2yLhyY=,tag:TS2KjbuT9YiIqUZMjRAxJg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
